table Member
	lineageTag: 29816e9c-866b-4571-80a0-f57fa9f8f181

	column MemberID
		dataType: string
		lineageTag: ebeffc0c-6583-4213-bb0a-349417aa296e
		summarizeBy: none
		sourceColumn: MemberID

		annotation SummarizationSetBy = Automatic

	column Name
		dataType: string
		lineageTag: 59a369e2-d4f9-4e59-9a9d-ce523f13e623
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

	column Email_Address
		dataType: string
		lineageTag: bbe14026-350d-4c26-a366-6328b89a81fd
		summarizeBy: none
		sourceColumn: Email_Address

		annotation SummarizationSetBy = Automatic

	column Joining_Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: ed49f878-6e10-4d4f-bd2d-406438ef2f96
		summarizeBy: none
		sourceColumn: Joining_Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Address
		dataType: string
		lineageTag: 410b6998-1574-40d2-81da-1bfa3917749c
		summarizeBy: none
		sourceColumn: Address

		annotation SummarizationSetBy = Automatic

	column Birth_Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4b8bdfaa-6929-4622-8a5c-e5f71742efc1
		summarizeBy: none
		sourceColumn: Birth_Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Gender
		dataType: string
		lineageTag: 4ab74a49-1cb2-4693-b404-b19f77252b4c
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column Marital_Status
		dataType: string
		lineageTag: a3379ccd-ad6a-4a70-aa33-04a559da9acf
		summarizeBy: none
		sourceColumn: Marital_Status

		annotation SummarizationSetBy = Automatic

	column Age
		dataType: int64
		formatString: 0
		lineageTag: 04cf6cc3-6829-4a32-a188-2b270d497c1f
		summarizeBy: none
		sourceColumn: Age

		annotation SummarizationSetBy = Automatic

		annotation __PBI_SemanticLinks = [{"LinkTarget":{"TableName":"Member","TableItemName":"Age (groups)","ObjectType":4},"LinkType":"UsedInGroup"}]

	column 'Age (groups)' =
			SWITCH(
				TRUE,
				ISBLANK('Member'[Age]),
				"(Blank)",
				'Member'[Age] IN {17,
					18,
					19},
				"(16-19)",
				'Member'[Age] IN {20,
					21,
					22,
					23,
					24,
					25,
					26,
					27,
					28},
				"(20-35)",
				'Member'[Age] IN {39,
					40,
					41,
					42,
					43,
					44,
					45,
					46,
					47,
					48,
					49},
				"(36-49)",
				'Member'[Age] IN {50,
					51,
					52,
					53,
					54,
					55,
					56,
					57,
					58,
					59,
					60,
					61,
					62,
					63,
					64,
					65},
				"(50-65)",
				'Member'[Age] IN {66,
					67,
					68,
					69,
					70,
					71,
					72,
					73,
					74,
					75,
					76,
					77,
					78,
					79,
					80,
					81,
					83,
					85,
					86,
					88,
					89,
					93,
					95},
				"66 Above",
				"Other"
			)
		lineageTag: ddc6b922-3171-46cd-8358-99dfd75df189
		summarizeBy: none

		extendedProperty GroupingMetadata =
				{
				  "version": 0,
				  "groupedColumns": [
				    {
				      "Column": {
				        "Expression": {
				          "SourceRef": {
				            "Entity": "Member"
				          }
				        },
				        "Property": "Age"
				      }
				    }
				  ]
				}

		annotation GroupingDesignState = {"Version":0,"Sources":[{"Name":"m","Entity":"Member"}],"GroupedColumns":[{"Column":{"Expression":{"SourceRef":{"Source":"m"}},"Property":"Age"}}],"GroupItems":[{"DisplayName":"(Blank)","BlankDefaultPlaceholder":true},{"DisplayName":"(16-19)","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"m"}},"Property":"Age"}}],"Values":[[{"Literal":{"Value":"17L"}}],[{"Literal":{"Value":"18L"}}],[{"Literal":{"Value":"19L"}}]]}}},{"DisplayName":"(20-35)","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"m"}},"Property":"Age"}}],"Values":[[{"Literal":{"Value":"20L"}}],[{"Literal":{"Value":"21L"}}],[{"Literal":{"Value":"22L"}}],[{"Literal":{"Value":"23L"}}],[{"Literal":{"Value":"24L"}}],[{"Literal":{"Value":"25L"}}],[{"Literal":{"Value":"26L"}}],[{"Literal":{"Value":"27L"}}],[{"Literal":{"Value":"28L"}}]]}}},{"DisplayName":"(36-49)","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"m"}},"Property":"Age"}}],"Values":[[{"Literal":{"Value":"39L"}}],[{"Literal":{"Value":"40L"}}],[{"Literal":{"Value":"41L"}}],[{"Literal":{"Value":"42L"}}],[{"Literal":{"Value":"43L"}}],[{"Literal":{"Value":"44L"}}],[{"Literal":{"Value":"45L"}}],[{"Literal":{"Value":"46L"}}],[{"Literal":{"Value":"47L"}}],[{"Literal":{"Value":"48L"}}],[{"Literal":{"Value":"49L"}}]]}}},{"DisplayName":"(50-65)","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"m"}},"Property":"Age"}}],"Values":[[{"Literal":{"Value":"50L"}}],[{"Literal":{"Value":"51L"}}],[{"Literal":{"Value":"52L"}}],[{"Literal":{"Value":"53L"}}],[{"Literal":{"Value":"54L"}}],[{"Literal":{"Value":"55L"}}],[{"Literal":{"Value":"56L"}}],[{"Literal":{"Value":"57L"}}],[{"Literal":{"Value":"58L"}}],[{"Literal":{"Value":"59L"}}],[{"Literal":{"Value":"60L"}}],[{"Literal":{"Value":"61L"}}],[{"Literal":{"Value":"62L"}}],[{"Literal":{"Value":"63L"}}],[{"Literal":{"Value":"64L"}}],[{"Literal":{"Value":"65L"}}]]}}},{"DisplayName":"66 Above","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"m"}},"Property":"Age"}}],"Values":[[{"Literal":{"Value":"66L"}}],[{"Literal":{"Value":"67L"}}],[{"Literal":{"Value":"68L"}}],[{"Literal":{"Value":"69L"}}],[{"Literal":{"Value":"70L"}}],[{"Literal":{"Value":"71L"}}],[{"Literal":{"Value":"72L"}}],[{"Literal":{"Value":"73L"}}],[{"Literal":{"Value":"74L"}}],[{"Literal":{"Value":"75L"}}],[{"Literal":{"Value":"76L"}}],[{"Literal":{"Value":"77L"}}],[{"Literal":{"Value":"78L"}}],[{"Literal":{"Value":"79L"}}],[{"Literal":{"Value":"80L"}}],[{"Literal":{"Value":"81L"}}],[{"Literal":{"Value":"83L"}}],[{"Literal":{"Value":"85L"}}],[{"Literal":{"Value":"86L"}}],[{"Literal":{"Value":"88L"}}],[{"Literal":{"Value":"89L"}}],[{"Literal":{"Value":"93L"}}],[{"Literal":{"Value":"95L"}}]]}}},{"DisplayName":"Other"}]}

		annotation SummarizationSetBy = Automatic

	column 'Age Group'
		dataType: string
		lineageTag: 1c7351fe-9dcd-4cd0-8ed0-7b35073161f9
		summarizeBy: none
		sourceColumn: Age Group

		annotation SummarizationSetBy = Automatic

	hierarchy 'Age (groups) Hierarchy'
		lineageTag: 7b383e0f-df13-4919-9976-b0a09f8ba893

		level 'Age (groups)'
			lineageTag: 58c18853-225c-46a6-a63d-23471d801d80
			column: 'Age (groups)'

		level Age
			lineageTag: 53277c84-cc1a-465b-acb6-6aab6cc1ec38
			column: Age

	partition Member = m
		mode: import
		source = ```
				let
				    Source = Sql.Databases("billieserver.database.windows.net"),
				    #"24HF" = Source{[Name="24HF_SSMS"]}[Data],
				    dbo_tblMember = #"24HF"{[Schema="dbo",Item="tblMember"]}[Data],
				    #"Inserted Age" = Table.AddColumn(dbo_tblMember, "Age", each Date.Year(DateTime.LocalNow()) - Date.Year([Birth_Date]), Int64.Type),
				    #"Added Custom" = Table.AddColumn(#"Inserted Age", "Age Group", each if [Age] >= 16 and [Age] <= 19 then 
				"16-19"
				else if [Age] >= 20 and [Age] <= 35 then 
				"20-35"
				else if [Age] >= 36 and [Age] <= 49 then 
				"36-49"
				else if [Age] >= 50 and [Age] <= 65 then 
				"50-65"
				else "66 Above")
				in
				    #"Added Custom"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

